#! /bin/bash

# In das Arbeitsverzeichnis wechseln.
RealScriptPath="$(dirname $(readlink -f $0))"
cd  $RealScriptPath/../solrmarc
echo "Now in $(pwd)"

JavaOpts="-Xmx2g -Xms2g"
JavaParams="-Dgnd.configdir=/opt/gvi/solrmarc -Dlog4j.configurationFile=log4j2.xml"
SolrMarc="-jar solrmarc_core.jar IndexDriver"
Config="-c gvi_index.properties"
Target="-u stdout"
Input="../scripts/testdata/oneTitle_hebis.xml"
Input="/data/input/gvi/swb/current/update/2018-05-03/work/TA-MARC-verbund-180502.mrc"
CMD="java $JavaOpts $JavaParams $SolrMarc $Config $Dirs $Target -? $Input"

echo "runing: $CMD"
$CMD
